In [1]:
s = "hi hello python"
s.split(' ')

['hi', 'hello', 'python']

In [2]:
planet = "Earth"
diameter = 12742

In [5]:
print( 'The diameter of {} is {} Kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 Kilometers.


In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [8]:
import numpy as np

In [9]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [12]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [13]:
import numpy as np
x = np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
arr = np.concatenate((a, b))
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
import pandas as pd

In [16]:
di = {'a': [1, 'df1'],'b': [2, 'df2'],'c': [3, 'fd3']}
df = pd.DataFrame(di)
df

a    b    c
0    1    2    3
1  df1  df2  fd3

In [18]:
dates = pd.date_range("1/1/2023", "10/02/2023")
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
df = pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24